" source this file from Vim's config file.

set nocompatible " be iMproved, required. ensure vim, not vi
syntax on

" DRY up the arguments to various calls to `source` in this file
let s:source_file_directory = '/home/rafael/git/dot-files/editors/vim/'
for fpath in split(globpath(s:source_file_directory, '*.vim'), '\n')
  exe 'source' fpath
endfor

" ------- Bundle options -------
" `syntastic`: lint the file on open, as well as save (lint on save is default)
let g:syntastic_check_on_open=1

" `vim-less`: mapping .less to .css, lessc is required
nnoremap <Leader>m :w <BAR> !lessc % > %:t:r.css<CR><space>

" `YouCompleteMe`: no popups & splits when presented with options
let g:ycm_add_preview_to_completeopt=0
set completeopt-=preview

" Session management
let g:session_autosave = 'no'
let g:session_autoload = 'no'

" ------- Autocmd, Filetype -------
" Language-specific settings should load automatically as long as they are in
" the `.vim/ftplugin/` directory. If not, then try putting all of them in the
" following file: `<PATH_TO_DOT_FILES_ROOT>/vim/autocmd.vim`

" Use eslint as syntax checker when working with a .jsx file.
" TODO: I'd like to be able to load this in './vim/ftplugin/javascript.vim', but
" am not having much success. Putting it here works, though it is kind of a
" duct tape solution.
autocmd FileType javascript.jsx let b:syntastic_checkers = ['eslint']
autocmd FileType javascript.jsx let g:syntastic_javascript_checkers = ['eslint']
autocmd FileType javascript let b:syntastic_checkers = ['eslint']
autocmd FileType javascript let g:syntastic_javascript_checkers = ['eslint']
" Allow JSX in normal JS files
autocmd FileType javascript let g:jsx_ext_required = 0

" ------- General configuration -------
set expandtab    " inserts a space whenever tab is pressed
set laststatus=2 " make the last window always have a status line
set shiftwidth=2 " num of space characters for indentation
set tabstop=2    " num of spaces inserted when tab is pressed
set textwidth=80 " max 80 characters before an automatic line break
set splitright   " vsplit will put a new buffer on the right side

" ------- Project-specific configuration -------
set exrc " allow project-specific configuration
" disable unsafe commands in project-specific `.vimrc`.
" (prevents commands from being run inside file unless it's owned by you.)
set secure
