# Overwrite, mix & match your own bash aliases here...

# quickly `cd` to common places
alias cd.eg='cd ~/git'
alias cd.dg='cd ~/Dropbox/git'
alias cd.js='cd ~/Documents/jobSearch'
alias cd.op='cd ~/git/odinProject/3_ruby-programming/3-ruby-on-the-web'
alias cd.it19='cd ~/git/clients/WFN/item19s/item19s-RoR'
alias cd.re='cd ~/git/RE-com'
alias cd.ap='cd ~/git/tuts-books/coursera/algorithms-princeton/notes'

# git aliases
alias gbr='git branch'
alias gci='git commit'
alias gco='git checkout'
alias gst='git status'
alias ga='git add'

# other commands
alias funJS='functional-javascript-workshop'
alias ssh-re='source $HOME/.dot-files/bash/ssh-re'

# set `n.`, depending on the desktop environment
case $XDG_CURRENT_DESKTOP in
  GNOME)
    alias n.='nautilus . &'
    ;;
  XFCE)
    alias n.='thunar . &'
    ;;
  *)
    echo "Set a value for 'n.' alias in your bash_alias file"
    ;;
esac

# aliases provided with a fresh install of Manjaro
alias l='ls -CF'
alias ls='ls --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'
alias ll='ls -l --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'
alias la='ls -la --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'
alias grep='grep --color=tty -d skip'
alias cp="cp -i"                      # confirm before overwriting something
alias df='df -h'                      # human-readable sizes
alias free='free -m'                  # show sizes in MB
alias np='nano PKGBUILD'
alias fixit='sudo rm -f /var/lib/pacman/db.lck && sudo pacman-mirrors -g && sudo pacman -Syyuu  && sudo pacman -Suu'
